### ISSUE TITLE
RPi Pico Project Generator - NMAKE -> invalid option 'j'

### ISSUE THREAD

**Issue by quizque** [ndabas/pico-setup-windows#17] opened 2021-11-24 19:51 UTC
When trying to enable the "Run build after generation" feature inside of the Raspberry Pi Pico Project Generator all files are generated fine but when it tries to build, it generates an error and fails.

Heres the options I have selected
![python_iTbq7fUBtt](https://user-images.githubusercontent.com/13785390/143293999-21e96c0f-7a22-4270-bed0-9147631d684c.png)

Here is the log of it generating just fine
![356Ew2gONF](https://user-images.githubusercontent.com/13785390/143304652-1282ee62-1eee-443f-a588-bb05f241fd18.png)

This is where the error occurs
![python_SFMpKLdVAX](https://user-images.githubusercontent.com/13785390/143304074-cd17c24c-b90b-4e5a-9590-e294b08f4872.png)

Here is a link to the project it generated
[ProjectName2.zip](https://github.com/ndabas/pico-setup-windows/files/7598407/ProjectName2.zip)

**Comment by ndabas** [comment] 2021-11-25 08:37
This appears to be a bug with the [Pico Project Generator](https://github.com/raspberrypi/pico-project-generator) and not this installer project. Please open an issue there.

A quick look shows that the problem is here: https://github.com/raspberrypi/pico-project-generator/blob/master/pico_project.py#L1179 -- `makeCmd = 'nmake -j ' + str(cpus)` -- `nmake` has no `-j` option. You could actually just submit a PR changing that line to `makeCmd = 'nmake'` which should fix it.

I'm closing this issue for now because there is nothing to do in this project.

**Closed as completed by ndabas** 2021-11-25 08:37 UTC

**Comment by JamesH65** [comment] 2021-11-25 09:48
I've fixed this on the pico project generator master branch. Thanks for the diagnosis.

**Comment by ndabas** [comment] 2021-11-25 12:17
@JamesH65 great, thank you!
